[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
figlet-rs = "0.1.5"
ansi_term = "0.12.1"
indicatif = { workspace = true }
crossterm = { workspace = true }
ratatui = "0.26"
rustyline = "12.0"


